name: CI/CD

env:
  PROJECT_ID: redblueapp
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/redblueapp/stock

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build Docker Image
        run: docker build -t stockticker:latest .

      - name: Tag and Push Image
        run: |
          docker tag stockticker:latest ${{ env.GAR_LOCATION }}/stockticker:latest
          docker push ${{ env.GAR_LOCATION }}/stockticker:latest
          
      - name: Deploy Container to Cloud Run
        run: |
          gcloud run deploy stockticker \
            --image ${{ env.GAR_LOCATION }}/stockticker:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
