name: CI

env:
  PROJECT_ID: redblueapp
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/redblueapp/stock
on:
   push:
    branches:
        - main

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
      - name: checkrepo
        uses: actions/checkout@v3
      - name: Dockerize ,build and push app
        run: docker build . | echo "Dockerized"
      - name: gcloud auth
        uses: google-github-actions/auth@v1
        with: 
          credentials_json: "${{ secrets.KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
        
      - name: "Tag image"
        run: docker tag us-central1-docker.pkg.dev/redblueapp/stock
        
      - name: "Push image"
        run: docker push ${{ env.GAR_LOCATION }}
        
        

