name: CI


on:
   push:
    branches:
        - main

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
      - name: checkrepo
        uses: actions/checkout@v3
      - name: Dockerize ,build and push app
        run: docker build . | echo "Dockerized"
        

